name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        run: |
          ssh -i ${{ secrets.EC2_KEY }} ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/immersive-sky-expereie-backend
            git pull origin main
            /usr/bin/pip3 install -r requirements.txt
            sudo systemctl restart myapp
          EOF
